#version 460

layout (local_size_x = 16, local_size_y = 16) in; // 16*16*1 lanes working together?!

layout (rgba16f,set = 0, binding = 0) uniform image2D image; // texture in

layout ( push_constant ) uniform constants {
	vec4 data1;
	vec4 data2;
	vec4 data3;
	vec4 data4;
} pc;

void main() {
	ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(image);
	
	if(texelCoord.x < size.x && texelCoord.y < size.y) {
		
		float blend = float(texelCoord.y) / (size.y);
		
		imageStore(image, texelCoord, mix(pc.data1, pc.data2, blend));
	}
}