#version 460
 // !!!!! AI PORTED https://www.shadertoy.com/view/wXcfWn !!!!!
 // the base version was hand written by some genius on shadertoy
layout (local_size_x = 16, local_size_y = 16) in;

layout (rgba32f, set = 0, binding = 0) uniform image2D image;

layout ( push_constant ) uniform constants {
    ivec2 offset;
    ivec2 updateRegion;
	float test;
} pc;

#define TAU 6.28318530717959
#define clamp01(x) clamp(x, 0.0, 1.0)

// -----------------------------------------------------------------------------
// NOISE FUNCTIONS
// -----------------------------------------------------------------------------

vec2 hash(vec2 p) {
    vec3 p3 = fract(vec3(p.xyx) * vec3(.1031, .1030, .0973));
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.xx + p3.yz) * p3.zy) * 2.0 - 1.0;
}

vec3 noised(vec2 p) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    
    vec2 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);
    vec2 du = 30.0 * f * f * (f * (f - 2.0) + 1.0);
    
    vec2 ga = hash(i + vec2(0.0, 0.0));
    vec2 gb = hash(i + vec2(1.0, 0.0));
    vec2 gc = hash(i + vec2(0.0, 1.0));
    vec2 gd = hash(i + vec2(1.0, 1.0));
    
    float va = dot(ga, f - vec2(0.0, 0.0));
    float vb = dot(gb, f - vec2(1.0, 0.0));
    float vc = dot(gc, f - vec2(0.0, 1.0));
    float vd = dot(gd, f - vec2(1.0, 1.0));

    return vec3(va + u.x * (vb - va) + u.y * (vc - va) + u.x * u.y * (va - vb - vc + vd),
        ga + u.x * (gb - ga) + u.y * (gc - ga) + u.x * u.y * (ga - gb - gc + gd) +
        du * (u.yx * (va - vb - vc + vd) + vec2(vb, vc) - va));
}

vec3 FractalNoise(vec2 p, float freq, int octaves, float lacunarity, float gain) {
    vec3 n = vec3(0.0);
    float nf = freq;
    float na = 1.0;
    for (int i = 0; i < octaves; i++) {
        n += noised(p * nf) * na * vec3(1.0, nf, nf);
        na *= gain;
        nf *= lacunarity;
    }
    return n;
}

vec4 PhacelleNoise(in vec2 p, vec2 normDir, float freq, float offset, float normalization) {
    vec2 sideDir = normDir.yx * vec2(-1.0, 1.0) * freq * TAU;
    offset *= TAU;

    vec2 pInt = floor(p);
    vec2 pFrac = fract(p);
    vec2 phaseDir = vec2(0.0);
    float weightSum = 0.0;
    
    for (int i = -1; i <= 2; i++) {
        for (int j = -1; j <= 2; j++) {
            vec2 gridOffset = vec2(i, j);
            vec2 gridPoint = pInt + gridOffset;
            vec2 randomOffset = hash(gridPoint) * 0.5;
            vec2 vectorFromCellPoint = pFrac - gridOffset - randomOffset;

            float sqrDist = dot(vectorFromCellPoint, vectorFromCellPoint);
            float weight = exp(-sqrDist * 2.0);
            weight = max(0.0, weight - 0.01111);

            weightSum += weight;

            float waveInput = dot(vectorFromCellPoint, sideDir) + offset;
            phaseDir += vec2(cos(waveInput), sin(waveInput)) * weight;
        }
    }

    vec2 interpolated = phaseDir / weightSum;
    float magnitude = sqrt(dot(interpolated, interpolated));
    magnitude = max(1.0 - normalization, magnitude);
    return vec4(interpolated / magnitude, sideDir);
}

// -----------------------------------------------------------------------------
// EROSION UTILITIES
// -----------------------------------------------------------------------------

float pow_inv(float t, float power) {
    return 1.0 - pow(1.0 - clamp01(t), power);
}

float ease_out(float t) {
    float v = 1.0 - clamp01(t);
    return 1.0 - v * v;
}

float smooth_start(float t, float smoothing) {
    if (t >= smoothing)
        return t - 0.5 * smoothing;
    return 0.5 * t * t / smoothing;
}

vec2 safe_normalize(vec2 n) {
    float l = length(n);
    return (abs(l) > 1e-10) ? (n / l) : n;  
}

// -----------------------------------------------------------------------------
// EROSION KERNEL
// -----------------------------------------------------------------------------

vec4 ErosionFilter(
    in vec2 p, vec3 heightAndSlope, float fadeTarget,
    float strength, float gullyWeight, float detail, vec4 rounding, vec4 onset, vec2 assumedSlope,
    float scale, int octaves, float lacunarity,
    float gain, float cellScale, float normalization,
    out float ridgeMap, out float debug
) {
    strength *= scale;
    fadeTarget = clamp(fadeTarget, -1.0, 1.0);
    
    vec3 inputHeightAndSlope = heightAndSlope;
    float freq = 1.0 / (scale * cellScale);
    float slopeLength = max(length(heightAndSlope.yz), 1e-10);
    float magnitude = 0.0;
    float roundingMult = 1.0;
    
    float roundingForInput = mix(rounding.y, rounding.x, clamp01(fadeTarget + 0.5)) * rounding.z;
    float combiMask = ease_out(smooth_start(slopeLength * onset.x, roundingForInput * onset.x));

    float ridgeMapCombiMask = ease_out(slopeLength * onset.z);
    float ridgeMapFadeTarget = fadeTarget;
    
    vec2 gullySlope = mix(heightAndSlope.yz, heightAndSlope.yz / slopeLength * assumedSlope.x, assumedSlope.y);
    
    for (int i = 0; i < octaves; i++) {
        vec4 phacelle = PhacelleNoise(p * freq, safe_normalize(gullySlope), cellScale, 0.25, normalization);
        phacelle.zw *= -freq;
        float sloping = abs(phacelle.y);
        
        gullySlope += sign(phacelle.y) * phacelle.zw * strength * gullyWeight;
        
        vec3 gullies = vec3(phacelle.x, phacelle.y * phacelle.zw);
        vec3 fadedGullies = mix(vec3(fadeTarget, 0.0, 0.0), gullies * gullyWeight, combiMask);
        heightAndSlope += fadedGullies * strength;
        magnitude += strength;
        
        fadeTarget = fadedGullies.x;
        
        float roundingForOctave = mix(rounding.y, rounding.x, clamp01(phacelle.x + 0.5)) * roundingMult;
        float newMask = ease_out(smooth_start(sloping * onset.y, roundingForOctave * onset.y));
        combiMask = pow_inv(combiMask, detail) * newMask;
        
        ridgeMapFadeTarget = mix(ridgeMapFadeTarget, gullies.x, ridgeMapCombiMask);
        float newRidgeMapMask = ease_out(sloping * onset.w);
        ridgeMapCombiMask = ridgeMapCombiMask * newRidgeMapMask;

        strength *= gain;
        freq *= lacunarity;
        roundingMult *= rounding.w;
    }
    
    ridgeMap = ridgeMapFadeTarget * (1.0 - ridgeMapCombiMask);
    debug = fadeTarget;
    
    vec3 heightAndSlopeDelta = heightAndSlope - inputHeightAndSlope;
    return vec4(heightAndSlopeDelta, magnitude);
}

// -----------------------------------------------------------------------------
// HEIGHTMAP GENERATOR
// -----------------------------------------------------------------------------

float GetHeight(vec2 p) {
    
    // -- EROSION SETTINGS --
    float EROSION_SCALE = 0.15;
    float EROSION_STRENGTH = 0.1; // Range 0.01 to 0.22 
    float EROSION_GULLY_WEIGHT = 0.5;
    float EROSION_DETAIL = 1.5;
    
    float ridgeRounding = 0.1;
    float creaseRounding = 0.0;
    vec4 EROSION_ROUNDING = vec4(ridgeRounding, creaseRounding, 0.1, 2.0);
    vec4 EROSION_ONSET = vec4(1.25, 1.25, 2.8, 1.5);
    vec2 EROSION_ASSUMED_SLOPE = vec2(0.7, 1.0);
    
    float EROSION_CELL_SCALE = 0.7;
    float EROSION_NORMALIZATION = 0.5;
    
    int EROSION_OCTAVES = 5;
    float EROSION_LACUNARITY = 2.0;
    float EROSION_GAIN = 0.5;
    vec2 TERRAIN_HEIGHT_OFFSET = vec2(-0.65, 0.0);

    // -- BASE NOISE SETTINGS --
    float HEIGHT_FREQUENCY = 3.0;
    float HEIGHT_AMP = 1.0f;
    int HEIGHT_OCTAVES = 3;
    float HEIGHT_LACUNARITY = 2.0;
    float HEIGHT_GAIN = 0.1;
    float heightFunctionScale = 1.0;
    
    // Base coordinate
    vec2 pHeight = p / heightFunctionScale;
    
    // Base FBM heights (returned in -1 to 1 range alongside derivates)
    vec3 n = FractalNoise(pHeight, HEIGHT_FREQUENCY, HEIGHT_OCTAVES, HEIGHT_LACUNARITY, HEIGHT_GAIN)
        * HEIGHT_AMP * vec3(heightFunctionScale, 1.0, 1.0);

    // Erosion Target
    float fadeTarget = clamp(n.x / (HEIGHT_AMP * 0.6), -1.0, 1.0);
    
    // Shift heights to 0..1 range
    n = n * 0.5 + vec3(0.5, 0.0, 0.0);

    float ridgeMap, debug;
    vec4 h = ErosionFilter(
        p, n, fadeTarget,
        EROSION_STRENGTH, EROSION_GULLY_WEIGHT, EROSION_DETAIL,
        EROSION_ROUNDING, EROSION_ONSET, EROSION_ASSUMED_SLOPE,
        EROSION_SCALE, EROSION_OCTAVES, EROSION_LACUNARITY,
        EROSION_GAIN, EROSION_CELL_SCALE, EROSION_NORMALIZATION,
        ridgeMap, debug
    );
    
    // Combine base geometry and eroded geometry
    float offset = mix(TERRAIN_HEIGHT_OFFSET.x, -fadeTarget, TERRAIN_HEIGHT_OFFSET.y) * h.w;
    float eroded = n.x + h.x + offset;
    
    return eroded;
}

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(image);
    
    if(texelCoord.x < size.x && texelCoord.y < size.y) {
        // Tweak the 0.005 scale value to zoom in/out on your world.
        vec2 p = vec2(texelCoord + pc.offset) * 0.005;
        
        float height = GetHeight(p * 0.05f);
		
		if(height < pc.test) height = 1000.0f;
    
        // Writing grayscale height data
        imageStore(image, texelCoord, vec4(height, height, height, 1.0));
    }
}